### ISSUE TITLE
Vote service throws a 500 and says it has a syntax error.

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-vote-service#99] opened 2022-02-03 07:58 UTC
I use the vote service. The backend tests in the main repo suddenly became failures:
FAILED tests/system/action/poll/test_reset.py::PollResetActionTest::test_reset_correct
FAILED tests/system/action/poll/test_reset.py::PollResetActionTest::test_reset_not_allowed_to_vote_again
FAILED tests/system/action/poll/test_reset.py::PollResetActionTest::test_reset_permissions
FAILED tests/system/action/poll/test_stop.py::PollStopActionTest::test_stop_correct
FAILED tests/system/action/poll/test_stop.py::PollStopActionTest::test_stop_entitled_users_at_stop_user_only_once
FAILED tests/system/action/poll/test_stop.py::PollStopActionTest::test_stop_permissions

Error message:
{'success': False, 'message': 'Vote service sends HTTP 500 with the following content: b\'{"error":"internal","message":"clearing counter: getting max score: calling zrange redis commant: ERR syntax error"}\'.'}

**Comment by jsangmeister** [comment] 2022-02-03 08:00
Duplicate of https://github.com/OpenSlides/openslides-vote-service/issues/98

**Closed by jsangmeister** 2022-02-03 08:00 UTC
Labels: bug, high
